# Generated by Django 4.2.7 on 2024-01-06 08:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0002_venue"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=20)),
                ("pr", models.CharField(max_length=20)),
                ("latitude", models.CharField(max_length=50)),
                ("longitude", models.CharField(max_length=50)),
            ],
        ),
    ]
